Doing corrections for the task one and two

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,33 +1,88 @@
 #!/usr/bin/env bash
-# Installs Nginx with the following configurations:
+# Script to duplicate web-01 configuration to web-02.
 
-# Update package list and install Nginx
-sudo apt-get update
-sudo apt-get install -y nginx
+# Uncomment the line below to enable debugging mode
+#set -x
 
-# Create directory and HTML files
-sudo mkdir /etc/nginx/html
-sudo touch /etc/nginx/html/index.html
-echo "Hello World!" > /etc/nginx/html/index.html
-sudo touch /etc/nginx/html/404.html
-echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
+echo -e "Updating and performing minor checks...\n"
 
-# Configure Nginx
-printf %s "server {
-    listen 80;
+function install() {
+    # Check if a given command is installed, if not, install it
+    command -v "$1" &> /dev/null
+
+    #shellcheck disable=SC2181
+    if [ $? -ne 0 ]; then
+        echo -e "    Installing: $1\n"
+        sudo apt-get update -y -qq && \
+            sudo apt-get install -y "$1" -qq
+        echo -e "\n"
+    else
+        echo -e "    ${1} is already installed.\n"
+    fi
+}
+
+# Install Nginx
+install nginx
+
+echo -e "\nSetting up some configurations...\n"
+
+# Allowing Nginx through the firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Giving user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+    sudo chown -R "$USER":"$USER" /var/www
+    sudo chmod -R 755 /var/www
+else
+    sudo mkdir -p /var/www
+    sudo chown -R "$USER":"$USER" /var/www
+    sudo chmod -R 755 /var/www
+fi
+
+# Create directories if not present
+for dir in /var/www/{html,error}; do
+    if ! [ -d "$dir" ]; then
+        mkdir -p "$dir"
+    fi
+done
+
+# Create new index page
+echo "Hello World!" > /var/www/html/index.html
+
+# Create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# Backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+# Nginx server configuration
+server_config=\
+"server {
+    listen 80 default_server;
     listen [::]:80 default_server;
+    root /var/www/html;
+    index index.html index.htm index.nginx-debian.html;
+    server_name _;
     add_header X-Served-By \$hostname;
-    root   /etc/nginx/html;
-    index  index.html index.htm;
-    location /redirect_me {
-        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
+    location / {
+        try_files \$uri \$uri/ =404;
     }
-    error_page 404 /404.html;
-    location /404 {
-      root /etc/nginx/html;
-      internal;
+    if (\$request_filename ~ redirect_me){
+        rewrite ^ https://th3-gr00t.tk/ permanent;
     }
-}" > /etc/nginx/sites-available/default
+    error_page 404 /error_404.html;
+    location = /error_404.html {
+        internal;
+    }
+}"
 
-# Restart Nginx to apply changes
-sudo service nginx restart
+# Apply the server configuration to the default Nginx site
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+# Start or restart Nginx service based on its status
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+    sudo service nginx start
+else
+    sudo service nginx restart
+fi
